on:
  workflow_call:
    secrets:
      kubeconfig:
        required: true
    inputs:
      kubernetes_directory:
        type: string
        description: 'The directory containing Kubernetes manifests'
        default: 'kubernetes'
      image:
        type: string
        description: 'The container image to deploy'
        required: true
      kubeconfig:
        type: string
        description: 'Kubeconfig file content'
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: azure/setup-kubectl@v4
          with:
            version: 'latest'
          id: install
        - uses: azure/k8s-set-context@v1
          with:
            method: kubeconfig
            kubeconfig: ${{ inputs.kubeconfig }}
          id: setcontext
        - uses: Azure/k8s-deploy@v3.1
          with:
            namespace: "default"
            manifests: ${{ inputs.kubernetes_directory }}
            images: ${{ inputs.image }}