on:
  workflow_call:
    secrets:
      kubeconfig:
        required: true
    inputs:
      application_name:
        type: string
        description: 'The name of the application to deploy'
        required: true
      helm_chart_path:
        type: string
        description: 'The Helm chart to use for deployment'
        required: true
      kubernetes_namespace:
        type: string
        description: 'The Kubernetes namespace to deploy to'
        required: false
        default: 'default'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
        - uses: azure/setup-kubectl@v4.0.1
          with:
            version: 'latest'
          id: install
        - uses: azure/k8s-set-context@v4.0.1
          with:
            method: kubeconfig
            kubeconfig: ${{ secrets.kubeconfig }}
          id: setcontext
        - name: Setup Helm
          uses: azure/setup-helm@v4.3.1
          with:
            version: 'latest'
        - name: Helm deployment
          run: |
            echo "Deploying ${{ inputs.application_name }} to namespace ${{ inputs.kubernetes_namespace }} using chart ${{ inputs.helm_chart }}"
            helm install ${{ inputs.application_name }} ${{ inputs.helm_chart }} --namespace ${{ inputs.kubernetes_namespace }} --wait --timeout 5m0s